spring.application.name: frontend
server.port: 17880
logging.level.ROOT: INFO
logging.level.org.springframework.web.client: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://AUTHORIZATION-SERVER/.well-known/jwks.json
      client:
        registration:
          my-client-credentials:
            provider: spring
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: message.read,message.write,orders:read
            client-name: messaging-client-client-credentials
        provider:
          spring:
            token-uri: http://AUTHORIZATION-SERVER/oauth/token